DROP TABLE IF EXISTS beanies;

CREATE TABLE beanies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    theme TEXT NOT NULL,
    animal TEXT NOT NULL,
    release_year INTEGER NOT NULL
);

CREATE TABLE beverages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    type TEXT NOT NULL,
);